// @generated by protoc-gen-es v2.6.3 with parameter "target=ts"
// @generated from file types/types.proto (package gorm.types, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/types.proto.
 */
export const file_types_types: GenFile = /*@__PURE__*/
  fileDesc("ChF0eXBlcy90eXBlcy5wcm90bxIKZ29ybS50eXBlcyIaCglVVUlEVmFsdWUSDQoFdmFsdWUYASABKAkiGgoJSlNPTlZhbHVlEg0KBXZhbHVlGAEgASgJIhUKBFVVSUQSDQoFdmFsdWUYASABKAkiGgoJSW5ldFZhbHVlEg0KBXZhbHVlGAEgASgJIhkKCFRpbWVPbmx5Eg0KBXZhbHVlGAEgASgNIhcKBkJpZ0ludBINCgV2YWx1ZRgBIAEoCUKaAQoOY29tLmdvcm0udHlwZXNCClR5cGVzUHJvdG9QAVozZ2l0aHViLmNvbS9pbmZvYmxveG9wZW4vcHJvdG9jLWdlbi1nb3JtL3R5cGVzO3R5cGVzogIDR1RYqgIKR29ybS5UeXBlc8oCCkdvcm1cVHlwZXPiAhZHb3JtXFR5cGVzXEdQQk1ldGFkYXRh6gILR29ybTo6VHlwZXNiBnByb3RvMw");

/**
 * @generated from message gorm.types.UUIDValue
 */
export type UUIDValue = Message<"gorm.types.UUIDValue"> & {
  /**
   * @generated from field: string value = 1;
   */
  value: string;
};

/**
 * Describes the message gorm.types.UUIDValue.
 * Use `create(UUIDValueSchema)` to create a new message.
 */
export const UUIDValueSchema: GenMessage<UUIDValue> = /*@__PURE__*/
  messageDesc(file_types_types, 0);

/**
 * @generated from message gorm.types.JSONValue
 */
export type JSONValue = Message<"gorm.types.JSONValue"> & {
  /**
   * @generated from field: string value = 1;
   */
  value: string;
};

/**
 * Describes the message gorm.types.JSONValue.
 * Use `create(JSONValueSchema)` to create a new message.
 */
export const JSONValueSchema: GenMessage<JSONValue> = /*@__PURE__*/
  messageDesc(file_types_types, 1);

/**
 * @generated from message gorm.types.UUID
 */
export type UUID = Message<"gorm.types.UUID"> & {
  /**
   * @generated from field: string value = 1;
   */
  value: string;
};

/**
 * Describes the message gorm.types.UUID.
 * Use `create(UUIDSchema)` to create a new message.
 */
export const UUIDSchema: GenMessage<UUID> = /*@__PURE__*/
  messageDesc(file_types_types, 2);

/**
 * @generated from message gorm.types.InetValue
 */
export type InetValue = Message<"gorm.types.InetValue"> & {
  /**
   * @generated from field: string value = 1;
   */
  value: string;
};

/**
 * Describes the message gorm.types.InetValue.
 * Use `create(InetValueSchema)` to create a new message.
 */
export const InetValueSchema: GenMessage<InetValue> = /*@__PURE__*/
  messageDesc(file_types_types, 3);

/**
 * @generated from message gorm.types.TimeOnly
 */
export type TimeOnly = Message<"gorm.types.TimeOnly"> & {
  /**
   * @generated from field: uint32 value = 1;
   */
  value: number;
};

/**
 * Describes the message gorm.types.TimeOnly.
 * Use `create(TimeOnlySchema)` to create a new message.
 */
export const TimeOnlySchema: GenMessage<TimeOnly> = /*@__PURE__*/
  messageDesc(file_types_types, 4);

/**
 * @generated from message gorm.types.BigInt
 */
export type BigInt = Message<"gorm.types.BigInt"> & {
  /**
   * @generated from field: string value = 1;
   */
  value: string;
};

/**
 * Describes the message gorm.types.BigInt.
 * Use `create(BigIntSchema)` to create a new message.
 */
export const BigIntSchema: GenMessage<BigInt> = /*@__PURE__*/
  messageDesc(file_types_types, 5);

