/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddWalletModal: typeof import('./src/components/modals/add-wallet-modal.vue')['default']
    BalanceItem: typeof import('./src/components/item/balance-item.vue')['default']
    BottomTabbar: typeof import('./src/components/bottom-tabbar.vue')['default']
    ClosePosition: typeof import('./src/components/modals/close-position.vue')['default']
    ComingSoon: typeof import('./src/components/coming-soon.vue')['default']
    CopyIcon: typeof import('./src/components/CopyIcon.vue')['default']
    CustomProgress: typeof import('./src/components/common/custom-progress.vue')['default']
    DepositModal: typeof import('./src/components/modals/deposit-modal.vue')['default']
    Empty: typeof import('./src/components/empty.vue')['default']
    ExchangeModal: typeof import('./src/components/modals/exchange-modal.vue')['default']
    Favorite: typeof import('./src/components/common/favorite.vue')['default']
    FlashSaleModal: typeof import('./src/components/modals/flash-sale-modal.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    OpenorderItem: typeof import('./src/components/item/openorder-item.vue')['default']
    PositionItem: typeof import('./src/components/item/position-item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchMarkModal: typeof import('./src/components/modals/search-mark-modal.vue')['default']
    SendModal: typeof import('./src/components/modals/send-modal.vue')['default']
    TokenInfo: typeof import('./src/components/token-info.vue')['default']
    TokenTable: typeof import('./src/components/tables/token-table.vue')['default']
    TrapezoidButtons: typeof import('./src/components/tab/TrapezoidButtons.vue')['default']
    VanBadge: typeof import('vant/es')['Badge']
    VanButton: typeof import('vant/es')['Button']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanCol: typeof import('vant/es')['Col']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanDivider: typeof import('vant/es')['Divider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRow: typeof import('vant/es')['Row']
    VanSearch: typeof import('vant/es')['Search']
    VanSlider: typeof import('vant/es')['Slider']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
