version: 3

vars:
  DOCKER_REGISTRY: ghcr.io/vxblocks/hyper_app
  GIT_REPO: https://github.com/VxBlocks/hyper_app

dotenv:
  - ".env"

tasks:
  deps:
    cmds:
      - go get -tool github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
      - go install github.com/golang/protobuf/protoc-gen-go@latest
      - go install github.com/infobloxopen/protoc-gen-gorm@latest
  gen:
    cmds:
      - rm -rf gen
      - buf generate
      # - go generate

  run:
    deps:
      - task: tunnel
      - task: go-run

  go-run:
    cmd: go run hyperliquid-server

  tunnel:
    cmds:
      - cloudflared tunnel run --token ${CLOUDFLARE_TUNNEL_TOKEN}

  build-api:
    cmd:
      task: build-docker
      vars:
        docker_tag: "{{.DOCKER_REGISTRY}}/api:{{.VERSION}}"
        dockerfile: "dockerfiles/api.dockerfile"

  build-docker:
    dir: "{{.DIR}}"
    vars:
      SOURCE: "{{.GIT_REPO}}"
      DOC: null
    cmds:
      - docker build -t {{.docker_tag}}
        {{if .dockerfile}} -f {{.dockerfile}} {{end}}
        {{range .build_arg}} --build-arg {{.}} {{end}}
        {{if .SOURCE}} --label org.opencontainers.image.source={{.SOURCE}} {{end}}
        {{if .DOC}} --label org.opencontainers.image.documentation={{.DOC}} {{end}}
        .
      - docker push {{.docker_tag}}
