// Copyright 2020-2025 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v2.6.3 with parameter "target=ts"
// @generated from file login/v1/login.proto (package login.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file login/v1/login.proto.
 */
export const file_login_v1_login: GenFile = /*@__PURE__*/
  fileDesc("ChRsb2dpbi92MS9sb2dpbi5wcm90bxIIbG9naW4udjEiPwoMTG9naW5SZXF1ZXN0Eg8KB2FkZHJlc3MYASABKAkSCwoDbXNnGAIgASgJEhEKCXNpZ25hdHVyZRgDIAEoCSIgCg1Mb2dpblJlc3BvbnNlEg8KB3Nlc3Npb24YASABKAkiNwoTTG9naW5Jc1ZhbGlkUmVxdWVzdBIPCgdzZXNzaW9uGAEgASgJEg8KB2FkZHJlc3MYAiABKAkiJQoUTG9naW5Jc1ZhbGlkUmVzcG9uc2USDQoFdmFsaWQYASABKAgiMQoNTG9nb3V0UmVxdWVzdBIPCgdzZXNzaW9uGAEgASgJEg8KB2FkZHJlc3MYAiABKAkiEAoOTG9nb3V0UmVzcG9uc2UiJwoSUmVnaXN0ZXJGY21SZXF1ZXN0EhEKCWZjbV90b2tlbhgBIAEoCSIVChNSZWdpc3RlckZjbVJlc3BvbnNlMqgCCgxMb2dpblNlcnZpY2USOgoFTG9naW4SFi5sb2dpbi52MS5Mb2dpblJlcXVlc3QaFy5sb2dpbi52MS5Mb2dpblJlc3BvbnNlIgASTwoMTG9naW5Jc1ZhbGlkEh0ubG9naW4udjEuTG9naW5Jc1ZhbGlkUmVxdWVzdBoeLmxvZ2luLnYxLkxvZ2luSXNWYWxpZFJlc3BvbnNlIgASPQoGTG9nb3V0EhcubG9naW4udjEuTG9nb3V0UmVxdWVzdBoYLmxvZ2luLnYxLkxvZ291dFJlc3BvbnNlIgASTAoLUmVnaXN0ZXJGY20SHC5sb2dpbi52MS5SZWdpc3RlckZjbVJlcXVlc3QaHS5sb2dpbi52MS5SZWdpc3RlckZjbVJlc3BvbnNlIgBChAEKDGNvbS5sb2dpbi52MUIKTG9naW5Qcm90b1ABWidoeXBlcmxpcXVpZC1zZXJ2ZXIvZ2VuL2xvZ2luL3YxO2xvZ2ludjGiAgNMWFiqAghMb2dpbi5WMcoCCExvZ2luXFYx4gIUTG9naW5cVjFcR1BCTWV0YWRhdGHqAglMb2dpbjo6VjFiBnByb3RvMw");

/**
 * Pet represents a pet in the pet store.
 *
 * @generated from message login.v1.LoginRequest
 */
export type LoginRequest = Message<"login.v1.LoginRequest"> & {
  /**
   * @generated from field: string address = 1;
   */
  address: string;

  /**
   * @generated from field: string msg = 2;
   */
  msg: string;

  /**
   * @generated from field: string signature = 3;
   */
  signature: string;
};

/**
 * Describes the message login.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_login_v1_login, 0);

/**
 * @generated from message login.v1.LoginResponse
 */
export type LoginResponse = Message<"login.v1.LoginResponse"> & {
  /**
   * @generated from field: string session = 1;
   */
  session: string;
};

/**
 * Describes the message login.v1.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_login_v1_login, 1);

/**
 * @generated from message login.v1.LoginIsValidRequest
 */
export type LoginIsValidRequest = Message<"login.v1.LoginIsValidRequest"> & {
  /**
   * @generated from field: string session = 1;
   */
  session: string;

  /**
   * @generated from field: string address = 2;
   */
  address: string;
};

/**
 * Describes the message login.v1.LoginIsValidRequest.
 * Use `create(LoginIsValidRequestSchema)` to create a new message.
 */
export const LoginIsValidRequestSchema: GenMessage<LoginIsValidRequest> = /*@__PURE__*/
  messageDesc(file_login_v1_login, 2);

/**
 * @generated from message login.v1.LoginIsValidResponse
 */
export type LoginIsValidResponse = Message<"login.v1.LoginIsValidResponse"> & {
  /**
   * @generated from field: bool valid = 1;
   */
  valid: boolean;
};

/**
 * Describes the message login.v1.LoginIsValidResponse.
 * Use `create(LoginIsValidResponseSchema)` to create a new message.
 */
export const LoginIsValidResponseSchema: GenMessage<LoginIsValidResponse> = /*@__PURE__*/
  messageDesc(file_login_v1_login, 3);

/**
 * @generated from message login.v1.LogoutRequest
 */
export type LogoutRequest = Message<"login.v1.LogoutRequest"> & {
  /**
   * @generated from field: string session = 1;
   */
  session: string;

  /**
   * @generated from field: string address = 2;
   */
  address: string;
};

/**
 * Describes the message login.v1.LogoutRequest.
 * Use `create(LogoutRequestSchema)` to create a new message.
 */
export const LogoutRequestSchema: GenMessage<LogoutRequest> = /*@__PURE__*/
  messageDesc(file_login_v1_login, 4);

/**
 * @generated from message login.v1.LogoutResponse
 */
export type LogoutResponse = Message<"login.v1.LogoutResponse"> & {
};

/**
 * Describes the message login.v1.LogoutResponse.
 * Use `create(LogoutResponseSchema)` to create a new message.
 */
export const LogoutResponseSchema: GenMessage<LogoutResponse> = /*@__PURE__*/
  messageDesc(file_login_v1_login, 5);

/**
 * @generated from message login.v1.RegisterFcmRequest
 */
export type RegisterFcmRequest = Message<"login.v1.RegisterFcmRequest"> & {
  /**
   * @generated from field: string fcm_token = 1;
   */
  fcmToken: string;
};

/**
 * Describes the message login.v1.RegisterFcmRequest.
 * Use `create(RegisterFcmRequestSchema)` to create a new message.
 */
export const RegisterFcmRequestSchema: GenMessage<RegisterFcmRequest> = /*@__PURE__*/
  messageDesc(file_login_v1_login, 6);

/**
 * @generated from message login.v1.RegisterFcmResponse
 */
export type RegisterFcmResponse = Message<"login.v1.RegisterFcmResponse"> & {
};

/**
 * Describes the message login.v1.RegisterFcmResponse.
 * Use `create(RegisterFcmResponseSchema)` to create a new message.
 */
export const RegisterFcmResponseSchema: GenMessage<RegisterFcmResponse> = /*@__PURE__*/
  messageDesc(file_login_v1_login, 7);

/**
 * @generated from service login.v1.LoginService
 */
export const LoginService: GenService<{
  /**
   * @generated from rpc login.v1.LoginService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
  /**
   * @generated from rpc login.v1.LoginService.LoginIsValid
   */
  loginIsValid: {
    methodKind: "unary";
    input: typeof LoginIsValidRequestSchema;
    output: typeof LoginIsValidResponseSchema;
  },
  /**
   * @generated from rpc login.v1.LoginService.Logout
   */
  logout: {
    methodKind: "unary";
    input: typeof LogoutRequestSchema;
    output: typeof LogoutResponseSchema;
  },
  /**
   * @generated from rpc login.v1.LoginService.RegisterFcm
   */
  registerFcm: {
    methodKind: "unary";
    input: typeof RegisterFcmRequestSchema;
    output: typeof RegisterFcmResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_login_v1_login, 0);

